### ISSUE TITLE
JS-Android  功能出错

### ISSUE THREAD

**Issue by tinybearc** [sdkbox/sdkbox-playphone-sample#19]
### playphone 版本：2.1.0.1

restore：输出结果为：
~~~
02-24 17:58:47.181: D/cocos2d-x debug info(11068): [IAP] restore
~~~

achievement test ：点击没反应，输出为：
~~~
2-24 17:49:15.880: W/System(8368): ClassLoader referenced unknown path: /system/framework/tcmclient.jar
~~~

remove_ads   double_coin     coin_package2     coin_package:  未知项目 购买失败

**Comment by ryanjjj7391** [comment]
重新测试：
remove_ads double_coin coin_package2 coin_package: 购买成功
Nite说可以close this issue
